### PR TITLE
test: target_node_name can now be passed in as a parameter

### PR DESCRIPTION
**Pull request by dillonroller**

### CODE REVIEW

**Comment by dillonroller** [comment]
Merge `am_rostest` then rerun actions

**Review by aroller — CHANGES_REQUESTED** [review]
Notice a relatively small change modified 34 files. This is due to each test repeating the syntax, rather than abstracting and referencing a common test file that could do most everything.  See [am_acsl_super](https://github.com/AutoModality/am_acsl_platform/blob/master/rostest/_acsl_super_rostest.test) has a common test file. 

Please consider refactoring to reduce the replication of your changes to so many files.

**Review by aroller — CHANGES_REQUESTED** [review]
Notice your use of `rosparam` with the node namespace declared, even though you are declaring the node in the same launch file. Using the param tag within the declaration of the node will assume the namespace of the node, so you don't have to repeat it.
```
<rosparam param="/abort_to_disarming_rostest/target_node_name">abort_to_disarming_rostest</rosparam>
```
would be
```
<test test-name="abort_to_disarming_rostest" pkg="am_super" type="abort_to_disarming_rostest" time-limit="20">
 <param .... />
</test>
```

see the [docs](http://wiki.ros.org/roslaunch/XML/test)  section `1.3 Elements`

**Review by aroller — COMMENTED** [review]
While your in there cleaning things up, or perhaps better in a subsequent pull request, consider enforcing a common naming pattern like I did in [am_acsl_platform CMakeLists.txt](https://github.com/AutoModality/am_acsl_platform/blob/master/CMakeLists.txt) which loops through test names and includes all of the files matching the common pattern. 

```
  #follow test naming convention of files in a folder and the cpp and launch have the test name with _rostest
  set(TEST_NAMES primary disconnected never_connected)
  foreach(TEST_NAME ${TEST_NAMES})
    add_rostest_gtest(${TEST_NAME}_rostest rostest/${TEST_NAME}/${TEST_NAME}_rostest.test rostest/acsl_super_rostest.cpp rostest/${TEST_NAME}/${TEST_NAME}_rostest.cpp)
  target_link_libraries(${TEST_NAME}_rostest ${catkin_LIBRARIES})
  endforeach()
```

**Review by aroller — CHANGES_REQUESTED** [review]
create a common launch file in the rostest dir that all tests call. Move the common code into that launch file.

**Review by aroller — APPROVED** [review]
Thanks for the strong finish.

**Pull request merged**
